services:
  db:
    image: postgres
    restart: always
    container_name: dolci-database
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  backend:
    build:
      context: ./backend/Pasticceria
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
 
  #frontend: