// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pasticceria.Data;

#nullable disable

namespace Pasticceria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612180028_DateTypeDolci")]
    partial class DateTypeDolci
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pasticceria.Models.Dolci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("ingredienti")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("prezzo")
                        .HasColumnType("real");

                    b.Property<int>("quantita")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Dolci");
                });
#pragma warning restore 612, 618
        }
    }
}
